### PR TITLE
Add log path collection:

### PR DESCRIPTION
**Pull request by mikowitz**
* Add LogPathCollector to collect and format data for submission
* Integrate the log path collector into the logger to properly, well, collect the log paths
* Implement an "internal" logger flow that bypasses log collection and use it throughout the client
* Add `Client.post` that will send serialized protobuf data to a given API endpoint

Also
===

* Comment out some thread locking in the config client that causes
  problems when datasources are set to "ALL", but the combination of URL
  and API key does not resolve correctly. There is more investigation to
  do, but at first pass it seems like some of this might be unnecessary
  as builtin types (like dicts) in Python may be thread safe on their
  own: https://docs.python.org/3/glossary.html#term-global-interpreter-lock

(ok, this might not be true: https://web.archive.org/web/20201108091210/http://effbot.org/pyfaq/what-kinds-of-global-value-mutation-are-thread-safe.htm, but I'm still not sure the code that's been commented out here is necessary. @semanticart maybe we can find a time to chat about this)

### CODE REVIEW

**Comment by semanticart** [comment]
Seems legit. Can I get a screenshot from the Prefab log level UI if you upload some example logging from (e.g.) a Django app?

**Comment by mikowitz** [comment]
Yep, I'll run some more live testing with it this evening.

**Comment by mikowitz** [comment]
@semanticart 
Screen Shot 2023-05-25 at 7 09 25 PM

**Comment by mikowitz** [comment]
@semanticart and with some django endpoints (also tested that setting values here was picked up by the client and works correctly in the endpoint logging)

Screen Shot 2023-05-25 at 7 53 01 PM

**Comment by jdwyah** [comment]
Maybe known, but these prefab things should nest and don't seem to be bc / instead of .

**Comment by mikowitz** [comment]
@jdwyah indeed. Those paths are now handled by the internal logger so won't show up anymore. I believe the logic I added to handle internal logging may have conflicted with some of the existing path formatting, but I think it's all fixed now

**Review by semanticart — APPROVED** [review]
Awesome. Looks like getting some more real-world testing shook out a few bugs 💃 

With you having addressed the nesting concern @jdwyah brought up, I'm 👍 on this

**Pull request merged**
