### PR TITLE
Add log-level context evaluation and tests

### PR DESCRIPTION
**Pull request by mikowitz**
Ensure that the current context is correctly read up when looking up
log levels

### CODE REVIEW

**Review by semanticart — APPROVED** [review]
LGTM. Does this get the 0.2.1 integration tests passing?

**Comment by mikowitz** [comment]
It is running and passing against the 0.2.0 integration tests.

**Comment by mikowitz** [comment]
Now it is running against 0.2.1

**Comment by semanticart** [comment]
Perfect 🚢

**Pull request merged**
